### PR TITLE
Updated rock-build in regards to the current autoproj2.0 version

### PR DESCRIPTION
**Pull request by goldhoorn**

### CODE REVIEW

**Comment by goldhoorn** [comment]
Do not merge before related issue is fixed

**Comment by doudou** [comment]
I could add a `# autoproj-version: VERSION` line at the top of autoproj's 2.0+ autoproj_bootstrap so that you can test on it and make the script backward-compatible. 2.0 will probably be in beta phase for a few months, that might be handy.

**Comment by goldhoorn** [comment]
On 21.10.2015 13:36, Sylvain Joyeux wrote:

> I could add a |# autoproj-version: VERSION| line at the top of
> autoproj's 2.0+ autoproj_bootstrap so that you can test on it and make
> the script backward-compatible. 2.0 will probably be in beta phase for
> a few months, that might be handy.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rock-core/base-build_server_scripts/pull/12#issuecomment-149861761.
> 
> could working, or a call `ruby autoproj_bootstrap --version` ?

## 

 Dipl.-Inf. Matthias Goldhoorn 
 Space and Underwater Robotic

 Universität Bremen
 FB 3 - Mathematik und Informatik
 AG Robotik
 Robert-Hooke-Straße 1
 28359 Bremen, Germany

 Zentrale: +49 421 178 45-6611

 Besuchsadresse der Nebengeschäftstelle: 
 Robert-Hooke-Straße 5
 28359 Bremen, Germany

 Tel.:    +49 421 178 45-4193
 Empfang: +49 421 178 45-6600
 Fax:     +49 421 178 45-4150
 E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

 Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by doudou** [comment]
Actually, I've re-added --no-color and --no-progress ... so we don't need that anymore.

**Pull request closed without merging**
