### PR TITLE
fixed doc generation

### PR DESCRIPTION
**Pull request by planthaber**

### CODE REVIEW

**Comment by planthaber** [comment]
Anyone?

Prior to this patch gems relies on a set GEM_HOME, which is not set anymore for autoproj 2, sourcing the env.sh in the subshell used fixes this

**Comment by planthaber** [comment]
Could someone how is allowed to do it please merge?

**Comment by 2maz** [comment]
Done. Since you are currently the maintainer, I added you as admin for this package as well.

**Comment by planthaber** [comment]
Thanks.

**Pull request merged**
